### ISSUE TITLE
Use a long timeout when sending releases

### ISSUE THREAD

**Issue by roncohen** [opbeat/opbeat_ruby#19]
Currently, sending release information from the gem uses the same timeout as sending error/exception information. There's really not a good reason for this, and while it's a good idea to have a low timeout for error/exception info, it can often be a disadvantage and lead to timeouts when sending release info.

**Comment by watson** [comment]
It's possible to overwrite the default 1 second timeouts using the two config parameters `timeout` and `open_timeout`: https://github.com/opbeat/opbeat_ruby#timeouts

Also, since v0.9.2 it's now possible to communicate with the Opbeat API using a background job or another thread. This way you can increase the timeouts without worrying that this holds up any ongoing client request: https://github.com/opbeat/opbeat_ruby#async-delivery
